"use client";

import Link from "next/link";
import { ArrowRight } from "lucide-react";
import AnimatedSection from "@/components/sections/AnimatedSection";
import { useLang } from "@/lib/i18n/LangContext";

const partnerTypes = [
  {
    title: "Nwvania Partner",
    subtitle: "For Freelancers & Independent Professionals",
    description:
      "If you provide a service — any service — and you work independently, Nwvania Partner is your professional home. List your services, receive orders, manage your earnings, and build your reputation within the ecosystem.",
    features: ["Professional profile", "Service marketplace listing", "Order & payment management", "Client reviews", "Earnings dashboard"],
    color: "#005CE6",
  },
  {
    title: "Nwvania Business",
    subtitle: "For Small & Medium Businesses",
    description:
      "Restaurants, clinics, retail stores, service centers — if you run a business, Nwvania Business manages everything: orders, customers, branches, staff, and invoicing.",
    features: ["POS & invoicing", "Multi-branch management", "Customer management", "Staff operations", "Business analytics"],
    color: "#059669",
  },
  {
    title: "Technology Partners",
    subtitle: "For Software Companies & Integrators",
    description:
      "Technology companies and system integrators can connect their products and services to the Nwvania ecosystem through the Developer API — reaching millions of users and businesses through one integration.",
    features: ["API access", "Revenue sharing", "Co-marketing", "Technical support", "Integration certification"],
    color: "#7C3AED",
  },
  {
    title: "Distribution Partners",
    subtitle: "For Logistics & Delivery Companies",
    description:
      "Logistics and delivery companies can operate within the Nwvania Mobility ecosystem — handling shipments generated by the platform's 220 applications and serving users across all sectors.",
    features: ["Order flow integration", "Fleet management", "Real-time tracking", "Performance analytics", "Settlement system"],
    color: "#EA580C",
  },
];

export default function PartnersContent() {
  const { t } = useLang();

  return (
    <>
      {/* HERO */}
      <section className="pt-32 pb-20 bg-gradient-to-b from-[#EEF4FF] to-white">
        <div className="max-w-7xl mx-auto px-6">
          <p className="animate-fade-up text-xs font-semibold text-[#005CE6] uppercase tracking-widest mb-4">
            {t.partners.label}
          </p>
          <h1 className="animate-fade-up-1 text-5xl md:text-6xl font-bold text-gray-900 leading-tight mb-6 max-w-3xl">
            {t.partners.headline}
          </h1>
          <p className="animate-fade-up-2 text-lg text-gray-500 max-w-2xl leading-relaxed">
            {t.partners.subtitle}
          </p>
        </div>
      </section>

      {/* PARTNER TYPES */}
      <section className="py-24 md:py-32">
        <div className="max-w-7xl mx-auto px-6 space-y-6">
          {partnerTypes.map((pt, i) => (
            <AnimatedSection key={i} delay={i * 80}>
              <div className="border border-gray-100 rounded-2xl p-8 md:p-10 hover:shadow-md transition-shadow duration-300">
                <div className="grid md:grid-cols-2 gap-10 items-start">
                  <div>
                    <div
                      className="inline-block w-10 h-1.5 rounded-full mb-5"
                      style={{ backgroundColor: pt.color }}
                    />
                    <h2 className="text-2xl font-bold text-gray-900 mb-1">{pt.title}</h2>
                    <p className="text-sm font-medium mb-5" style={{ color: pt.color }}>{pt.subtitle}</p>
                    <p className="text-gray-500 leading-relaxed">{pt.description}</p>
                  </div>
                  <div>
                    <div className="text-xs font-semibold text-gray-400 uppercase tracking-wider mb-4">
                      What you get
                    </div>
                    <ul className="space-y-3" role="list">
                      {pt.features.map((f) => (
                        <li key={f} className="flex items-center gap-3 text-sm text-gray-700">
                          <div
                            className="w-4 h-4 rounded-full flex items-center justify-center shrink-0"
                            style={{ backgroundColor: `${pt.color}20` }}
                          >
                            <div className="w-1.5 h-1.5 rounded-full" style={{ backgroundColor: pt.color }} />
                          </div>
                          {f}
                        </li>
                      ))}
                    </ul>
                  </div>
                </div>
              </div>
            </AnimatedSection>
          ))}
        </div>
      </section>

      {/* CTA */}
      <section className="py-24 bg-gray-50">
        <div className="max-w-7xl mx-auto px-6 text-center">
          <AnimatedSection>
            <h2 className="text-3xl md:text-5xl font-bold text-gray-900 mb-6">
              {t.partners.ctaTitle}
            </h2>
            <p className="text-gray-500 text-lg max-w-xl mx-auto mb-10">
              {t.partners.ctaSubtitle}
            </p>
            <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
              <Link
                href="/early-access"
                className="bg-black text-white px-8 py-4 rounded-full text-sm font-medium hover:bg-gray-800 transition-colors flex items-center gap-2"
              >
                {t.partners.ctaButton} <ArrowRight size={16} />
              </Link>
              <Link
                href="/contact"
                className="border border-gray-200 text-gray-700 px-8 py-4 rounded-full text-sm font-medium hover:bg-white transition-colors"
              >
                {t.common.contactUs}
              </Link>
            </div>
          </AnimatedSection>
        </div>
      </section>
    </>
  );
}
